lib/pwd_reset_web/router.ex
defmodule PwdResetWeb.Router do
  use PwdResetWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PwdResetWeb do
    pipe_through :browser

    get "/", UserController, :index
    get "/login", UserController, :show
    post "/login", UserController, :login
    resources "/user", UserController
    get "/reset", ResetController, :index
    post "/reset", ResetController, :show
    get "/reset/:token", ResetController, :check
    post "/reset/:token", ResetController, :update

  end

  # Other scopes may use custom stacks.
  # scope "/api", PwdResetWeb do
  #   pipe_through :api
  # end
end

lib/pwd_reset/user.ex
defmodule PwdReset.User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field :email, :string
    field :name, :string
    field :password, :string
    field :token, :string

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :email, :password, :token])
    |> validate_required([:email, :password])
    |> validate_format(:email, ~r/@/)
    |> unique_constraint(:email)
  end
end

lib/pwd_reset_web/controllers/user_controller.ex
defmodule PwdResetWeb.UserController do
  use PwdResetWeb, :controller

  alias PwdReset.UserHandler

  def index(conn, _params) do
    render conn, "index.html"
  end

  def show(conn, _params) do
    render conn, "show.html", csrf: get_csrf_token()
  end

  def login(conn, %{"user" => %{"email" => email, "password" => password}}) do
    user = UserHandler.get_user_by_email(email)
    case user do
      {:error, reason} ->
        conn
        |> put_flash(:error, reason)
        |> redirect(to: Routes.user_path(conn, :show))
      {:ok, user} ->
        if user.password == password do
          conn
          |> put_flash(:info, "Succesfully logged in!")
          |> redirect(to: Routes.user_path(conn, :index))
        else
          conn
          |> put_flash(:error, "Wrong password.")
          |> redirect(to: Routes.user_path(conn, :show))
        end
    end
  end

  def new(conn, _params) do
    render conn, "new.html", csrf: get_csrf_token()
  end

  def create(conn, %{"user" => %{"email" => email, "password" => password, "password_confirmation" => password_confirmation}}) do

    if password == password_confirmation do
      values = %{email: email, password: password}
      result = UserHandler.create_user(values)

      case result do
        {:error, changeset} ->
          {key, {reason, _constraint}} = List.first(changeset.errors)
          message = Atom.to_string(key) |> String.capitalize()
          message = message <> " " <> reason <> "."
          conn
          |> put_flash(:error, "User creation failed. " <> message)
          |> redirect(to: Routes.user_path(conn, :new))
        {:ok, user} ->
          conn
          |> put_flash(:info, "User created using email " <> user.email)
          |> redirect(to: Routes.user_path(conn, :index))
      end
    else
      conn
      |> put_flash(:error, "Passwords did not match.")
      |> redirect(to: Routes.user_path(conn, :new))
    end

  end
end

lib/pwd_reset_web/views/user_view.ex
defmodule PwdResetWeb.UserView do
  use PwdResetWeb, :view
end

lib/pwd_reset_web/templates/user/index.html.eex
<h1>Hello</h1>
<div>
  <h2>What do you want to do today?</h2>
</div>
<div>
  <a href="<%= Routes.user_path(@conn, :new) %>" class="button">Register</a>
  <a href="<%= Routes.user_path(@conn, :show) %>" class="button">Login</a>
  <a href="<%= Routes.reset_path(@conn, :index) %>" class="button">Reset password</a>
</div>

lib/pwd_reset_web/templates/user/new.html.eex
<h1>New user</h1>
<form action="/user" method="post">
  <div class="form-group">
    <input type="hidden" name="_csrf_token" value="<%= @csrf %>">

    <label for=="user[email]">Email</label>
    <input type="email" name="user[email]" class="form-control" />

    <label for=="user[password]">Password</label>
    <input type="password" name="user[password]" class="form-control" />

    <label for=="user[password_confirmation]">Confirm password</label>
    <input type="password" name="user[password_confirmation]" class="form-control" />

  </div>
  <button type="submit" class="btn btn-primary">Save</button>
  <div>
    <a href="/">Cancel</a>
  </div>
</form>

lib/pwd_reset_web/templates/user/show.html.eex
<h1>Login</h1>
<form action="<%= Routes.user_path(@conn, :login) %>" method="post">
  <div class="form-group">
    <input type="hidden" name="_csrf_token" value="<%= @csrf %>">

    <label for=="user[email]">Email</label>
    <input type="email" name="user[email]" class="form-control" />

    <label for=="user[password]">Password</label>
    <input type="password" name="user[password]" class="form-control" />

  </div>
  <button type="submit" class="btn btn-primary">Login</button>
  <div>
    <a href="/">Cancel</a>
  </div>
</form>